steps:
  # Step 1: Check/create Artifact Registry
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        if ! gcloud artifacts repositories describe amjad-repo --location=us-central1 --project=enhub-cloud-interns; then
          echo "Repository doesn't exist. Creating now."
          gcloud artifacts repositories create amjad-repo --repository-format=docker --location=us-central1 --project=enhub-cloud-interns
        else
          echo "Repository already exists."
        fi

  # Step 2: Build Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'us-central1-docker.pkg.dev/enhub-cloud-interns/amjad-repo/my-app:$BUILD_ID', '.']

  # Step 3: Push Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-central1-docker.pkg.dev/enhub-cloud-interns/amjad-repo/my-app:$BUILD_ID']

  # Step 4: Create a release in Cloud Deploy
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gcloud deploy releases create release-$BUILD_ID \
          --project=enhub-cloud-interns \
          --region=us-central1 \
          --delivery-pipeline=demo-amjad \
          --images=my-app=us-central1-docker.pkg.dev/enhub-cloud-interns/amjad-repo/my-app:$BUILD_ID

images:
  - 'us-central1-docker.pkg.dev/enhub-cloud-interns/amjad-repo/my-app:$BUILD_ID'

options:
  logging: CLOUD_LOGGING_ONLY
