steps:
  # Step 1: Check/create Artifact Registry
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        if ! gcloud artifacts repositories describe amjad-repo --location=us-central1 --project=enhub-cloud-interns; then
          echo "Repository doesn't exist. Creating now."
          gcloud artifacts repositories create amjad-repo --repository-format=docker --location=us-central1 --project=enhub-cloud-interns
        else
          echo "Repository already exists."
        fi

  # Step 2: Build Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'us-central1-docker.pkg.dev/enhub-cloud-interns/amjad-repo/my-app:$BUILD_ID', '.']

  # Step 3: Push Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-central1-docker.pkg.dev/enhub-cloud-interns/amjad-repo/my-app:$BUILD_ID']

  # Step 4: Create a Cloud Deploy release
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    args:
      - 'deploy'
      - 'releases'
      - 'create'
      - 'release-$BUILD_ID'
      - '--delivery-pipeline=demo-amjad'
      - '--region=us-central1'
      - '--images=my-app=us-central1-docker.pkg.dev/enhub-cloud-interns/amjad-repo/my-app:$BUILD_ID'
      - '--project=enhub-cloud-interns'

images:
  - 'us-central1-docker.pkg.dev/enhub-cloud-interns/amjad-repo/my-app:$BUILD_ID'

options:
  logging: CLOUD_LOGGING_ONLY
