steps:
  # Step 1: Check/Create Artifact Registry
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        if ! gcloud artifacts repositories describe amjad-repo --location=us-central1 --project=enhub-cloud-interns; then
          echo "Repository doesn't exist. Creating now."
          gcloud artifacts repositories create amjad-repo --repository-format=docker --location=us-central1 --project=enhub-cloud-interns
        else
          echo "Repository already exists."
        fi

  # Step 2: Build Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'us-central1-docker.pkg.dev/enhub-cloud-interns/amjad-repo/my-app:latest', '.']

  # Step 3: Push Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-central1-docker.pkg.dev/enhub-cloud-interns/amjad-repo/my-app:latest']

  # Step 4: Create Delivery Pipeline (Cloud Deploy)
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'deploy'
      - 'delivery-pipelines'
      - 'create'
      - 'my-pipeline'
      - '--region=us-central1'
      - '--project=enhub-cloud-interns'
      - '--file=-'  # This will apply the pipeline from stdin

  # Step 5: Apply Cloud Run Targets (Cloud Deploy)
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'deploy'
      - 'targets'
      - 'apply'
      - '--file=-'  # This will apply the target configuration from stdin

  # Step 6: Trigger Cloud Deploy release
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'deploy'
      - 'releases'
      - 'create'
      - '--delivery-pipeline=my-pipeline'
      - '--region=us-central1'
      - '--project=enhub-cloud-interns'
      - '--image=us-central1-docker.pkg.dev/enhub-cloud-interns/amjad-repo/my-app:latest'

  # Step 7: Promote the release to production (if needed)
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'deploy'
      - 'releases'
      - 'promote'
      - '--release=my-release'
      - '--delivery-pipeline=my-pipeline'
      - '--region=us-central1'
      - '--project=enhub-cloud-interns'

images:
  - 'us-central1-docker.pkg.dev/enhub-cloud-interns/amjad-repo/my-app:latest'

options:
  logging: CLOUD_LOGGING_ONLY
